# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 06 Mar 2016 21:10:20 +0000
*               @ALL          1
*               @user         8
