<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jcherven
 * Date: Wed, 09 Mar 2016 16:09:13 -0500
 */

$conf['title'] = 'Storage, Backup, & Recovery with ZFS on Linux';
$conf['template'] = 'codowik-master';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['securecookie'] = 0;
$conf['proxy']['user'] = 'jcherven';
$conf['proxy']['pass'] = '<b>S2F0by44My5UYWtvLjgzLg==';

// end auto-generated content
